export const DEFAULT_POMO_DURATION_MINUTES = 25;
export const MAX_POMO_DURATION_MINUTES = 120;
export const DEFAULT_EVENT_DURATION_MINUTES = 60;
export const DEFAULT_FAILURE_COST_CENTS = 100;
export const DEFAULT_FAILURE_COST_EUROS = "1.00";
export const MAX_SUBTASKS_PER_TASK = 20;
